In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv("boston_house_prices.csv",header=1)
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [11]:
df.rename(columns={"MEDV": "Price"}, inplace=True)

In [12]:
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Price
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [13]:
## Dividing the dataset into independent and dependent features

X = df.drop("Price", axis=1)
y = df["Price"]

In [26]:
## Linear Regression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

lin_reg = LinearRegression()
mse = cross_val_score(lin_reg, X, y, scoring="neg_mean_squared_error", cv=5)
mean_mse = np.mean(mse)
print("Mean MSE:", mean_mse)

Mean MSE: -37.13180746769923

In [27]:
## Ridge Regression
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

param_grid = {'alpha': [1e-15,1e-10,1e-8,1e-3,1e-2,0.1, 1.0, 10.0,20]}
ridge_reg = GridSearchCV(Ridge(), param_grid, scoring="neg_mean_squared_error", cv=5)
ridge_reg.fit(X, y)
print("Best alpha for Ridge Regression:", ridge_reg.best_params_['alpha'])
mean_mse_ridge = -ridge_reg.best_score_
print("Mean MSE for Ridge Regression:", mean_mse_ridge)

Best alpha for Ridge Regression: 20
Mean MSE for Ridge Regression: 32.38025025182519

In [28]:
## Lasso Regression
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV

param_grid = {'alpha': [1e-15,1e-10,1e-8,1e-3,1e-2,0.1, 1.0, 10.0,20]}
lasso_reg = GridSearchCV(Lasso(), param_grid, scoring="neg_mean_squared_error", cv=5)
lasso_reg.fit(X, y)
print("Best alpha for Lasso Regression:", lasso_reg.best_params_['alpha'])
mean_mse_lasso = -lasso_reg.best_score_
print("Mean MSE for Lasso Regression:", mean_mse_lasso)

c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.273e+03, tolerance: 3.919e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.042e+03, tolerance: 3.307e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.643e+03, tolerance: 2.814e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.193e+03, tolerance: 3.307e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.554e+03, tolerance: 3.481e+00
  model = cd_fast.enet_coordinate_descent(

Best alpha for Lasso Regression: 0.1
Mean MSE for Lasso Regression: 34.83043231820268

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [30]:
## Linear Regression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

lin_reg = LinearRegression()
mse = cross_val_score(lin_reg, X_train, y_train, scoring="neg_mean_squared_error", cv=5)
mean_mse = np.mean(mse)
print("Mean MSE:", mean_mse)

Mean MSE: -23.654418270304625

In [31]:
## Ridge Regression
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

param_grid = {'alpha': [1e-15,1e-10,1e-8,1e-3,1e-2,0.1, 1.0, 10.0,20]}
ridge_reg = GridSearchCV(Ridge(), param_grid, scoring="neg_mean_squared_error", cv=5)
ridge_reg.fit(X_train, y_train)
print("Best alpha for Ridge Regression:", ridge_reg.best_params_['alpha'])
mean_mse_ridge = -ridge_reg.best_score_
print("Mean MSE for Ridge Regression:", mean_mse_ridge)

Best alpha for Ridge Regression: 1e-15
Mean MSE for Ridge Regression: 23.65441827030464

In [32]:
## Lasso Regression
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV

param_grid = {'alpha': [1e-15,1e-10,1e-8,1e-3,1e-2,0.1, 1.0, 10.0,20]}
lasso_reg = GridSearchCV(Lasso(), param_grid, scoring="neg_mean_squared_error", cv=5)
lasso_reg.fit(X_train, y_train)
print("Best alpha for Lasso Regression:", lasso_reg.best_params_['alpha'])
mean_mse_lasso = -lasso_reg.best_score_
print("Mean MSE for Lasso Regression:", mean_mse_lasso)

c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.258e+03, tolerance: 2.882e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.569e+03, tolerance: 2.764e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.236e+03, tolerance: 2.710e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.272e+03, tolerance: 2.730e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.899e+03, tolerance: 2.948e+00
  model = cd_fast.enet_coordinate_descent(

Best alpha for Lasso Regression: 1e-15
Mean MSE for Lasso Regression: 23.654418270304653

c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.132e+03, tolerance: 3.510e+00
  model = cd_fast.enet_coordinate_descent(